#############
# MESA DE 6 #
#############
BTN = 'BTN' # Dealer/button
SB = 'SB' # Small Blind
BB = 'BB' # Big Blind
UTG = 'UTG' # Under the Gun
MP = 'MP' # Middle Position 
CO = 'CO' # Cut Off

##########
# DEALER #
##########
DEALER_ESTA_ABAJO = "DEALER_ESTA_ABAJO"
DEALER_ESTA_IZQUIERDA_ABAJO = "DEALER_ESTA_IZQUIERDA_ABAJO" 
DEALER_ESTA_IZQUIERDA_ARRIBA = "DEALER_ESTA_IZQUIERDA_ARRIBA" 
DEALER_ESTA_ARRIBA = "DEALER_ESTA_ARRIBA" 
DEALER_ESTA_DERECHA_ARRIBA = "DEALER_ESTA_DERECHA_ARRIBA"
DEALER_ESTA_DERECHA_ABAJO = "DEALER_ESTA_DERECHA_ABAJO" 